const KEY="brm5-ops-v2";let plans=JSON.parse(localStorage.getItem(KEY)||"[]"),editing=null;
const $=x=>document.getElementById(x), V=x=>$(x).value;
const AIRCRAFT={
  "UH-60V 'BLACK HAWK'":{role:"UTILITY",speed:"294 MPH",capacity:"49",note:"Utility / troop transport"},
  "NH90 TTH":{role:"UTILITY",speed:"300 MPH",capacity:"49",note:"Utility / troop transport"},
  "CH-47D 'CHINOOK'":{role:"MEDIUM-LIFT",speed:"315 MPH",capacity:"49 + cargo",note:"Medium-lift / cargo"},
  "Mi-8MTV-2 'HIP'":{role:"MEDIUM-LIFT",speed:"249 MPH",capacity:"49 + cargo",note:"Medium-lift / cargo"},
  "CH-53D 'SEA STALLION'":{role:"HEAVY-LIFT",speed:"315 MPH",capacity:"49 + heavy cargo",note:"Heavy-lift / cargo"},
  "MH-6 'LITTLE BIRD'":{role:"LIGHT ASSAULT",speed:"200 MPH",capacity:"64",note:"Light assault / insertion"}
};
function updateAircraftMeta(){const a=AIRCRAFT[V("aircraft")];if(!a){$("aircraftMeta").textContent="";return}$('aircraftMeta').innerHTML=`<b>${a.role}</b> · ${a.speed}<br><span>${a.capacity} seats / capacity · ${a.note}</span>`;}

function localNow(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}$("datetime").value=localNow();
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function addWp(d={}){let r=document.createElement("div");r.className="waypoint";r.innerHTML=`<div class="wpnum"></div><label>NAME<input class="wn" placeholder="LZ / FOB / CP" value="${esc(d.name)}"></label><label>GRID<input class="wg" placeholder="02 345 / 01 780" value="${esc(d.grid)}"></label><label>ALT<input class="wa" placeholder="500 AGL" value="${esc(d.alt)}"></label><label>ACTION<input class="wx" placeholder="LAND / HOLD / RTB" value="${esc(d.action)}"></label><button class="x">×</button>`;r.querySelector(".x").onclick=()=>{r.remove();renumber()};$("wps").append(r);renumber()}
function renumber(){[...document.querySelectorAll(".waypoint")].forEach((r,i)=>r.querySelector(".wpnum").textContent=String(i+1).padStart(2,"0"));let n=document.querySelectorAll(".waypoint").length;$("route").textContent=n?`${n} WAYPOINT${n>1?"S":""} DEFINED // MAP OVERLAY ACTIVE`:"NO WAYPOINTS DEFINED";draw()}
function collect(){return {id:editing||crypto.randomUUID(),saved:new Date().toISOString(),mission:V("mission")||"UNTITLED MISSION",datetime:V("datetime"),type:V("type"),status:V("status"),notes:V("notes"),rules:V("rules"),formation:V("formation"),alt:V("alt"),weather:V("weather"),load:V("load"),comms:V("comms"),aircraft:V("aircraft"),callsign:V("callsign"),wps:[...document.querySelectorAll(".waypoint")].map(r=>({name:r.querySelector(".wn").value,grid:r.querySelector(".wg").value,alt:r.querySelector(".wa").value,action:r.querySelector(".wx").value}))}}
function save(){let p=collect(),i=plans.findIndex(x=>x.id===p.id);if(i<0)plans.unshift(p);else plans[i]=p;localStorage.setItem(KEY,JSON.stringify(plans));editing=p.id;renderSaved();renderBrief();alert("Flight plan saved locally.")} 
function load(p){editing=p.id;["mission","datetime","type","status","notes","rules","formation","alt","weather","load","comms","aircraft","callsign"].forEach(k=>$(k).value=p[k]??"");$("wps").innerHTML="";p.wps.forEach(addWp);show("planner");renderBrief()}
function reset(){editing=null;$("mission").value="";$("datetime").value=localNow();$("notes").value="";$("wps").innerHTML="";addWp({name:"START",alt:"500 AGL",action:"DEPART"});renderBrief()}
function renderSaved(){$("count").textContent=plans.length;$("savedList").innerHTML=plans.length?plans.map(p=>`<div class="saved"><div><strong>${esc(p.mission)}</strong><div class="meta">${esc(p.callsign)} · ${esc(p.type)} · ${p.wps.length} WP · ${new Date(p.saved).toLocaleString()}</div></div><div><button class="btn mini load" data-id="${p.id}">LOAD</button><button class="btn mini danger del" data-id="${p.id}">DELETE</button></div></div>`).join(""):`<div class="panel"><span class="help">NO SAVED FLIGHT PLANS.</span></div>`;document.querySelectorAll(".load").forEach(b=>b.onclick=()=>load(plans.find(p=>p.id===b.dataset.id)));document.querySelectorAll(".del").forEach(b=>b.onclick=()=>{plans=plans.filter(p=>p.id!==b.dataset.id);localStorage.setItem(KEY,JSON.stringify(plans));renderSaved()})}
function field(a,b){return `<div class="bf"><span>${a}</span><b>${esc(b||"—")}</b></div>`}
function renderBrief(){let p=collect();$("briefCard").innerHTML=`<div class="brief"><div class="briefhead"><h2>${esc(p.mission)}</h2><div>${esc(p.callsign)} // ${esc(p.aircraft)}</div></div><div class="briefgrid">${field("MISSION",p.type)}${field("DATE / TIME",p.datetime?new Date(p.datetime).toLocaleString():"—")}${field("FLIGHT RULES",p.rules)}${field("FORMATION",p.formation)}${field("ALTITUDE",p.alt)}${field("WEATHER",p.weather)}${field("LOAD / CONFIG",p.load)}${field("STATUS",p.status)}${field("COMMS",p.comms)}</div><table><thead><tr><th>WP</th><th>NAME</th><th>GRID</th><th>ALT</th><th>ACTION</th></tr></thead><tbody>${p.wps.map((w,i)=>`<tr><td>${i+1}</td><td>${esc(w.name)}</td><td>${esc(w.grid)}</td><td>${esc(w.alt)}</td><td>${esc(w.action)}</td></tr>`).join("")}</tbody></table><div class="notes"><b>MISSION NOTES</b><br>${esc(p.notes||"None.")}</div></div>`}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="saved")renderSaved();if(id==="brief")renderBrief()}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>show(n.dataset.page));$("add").onclick=()=>addWp();$("save").onclick=save;$("new").onclick=reset;$("clear").onclick=()=>{if(confirm("Delete all saved plans?")){plans=[];localStorage.removeItem(KEY);renderSaved()}};$("clearMap").onclick=()=>{$("wps").innerHTML="";renumber();};
function gridFromClick(e){let box=$("map").getBoundingClientRect(),x=(e.clientX-box.left)/box.width,y=(e.clientY-box.top)/box.height;let east=Math.max(0,Math.min(7.999,x*8)),north=Math.max(0,Math.min(3.999,(1-y)*4));let eMajor=Math.floor(east),nMajor=Math.floor(north),eMinor=Math.floor((east-eMajor)*1000),nMinor=Math.floor((north-nMajor)*1000);return `${String(eMajor).padStart(2,"0")} ${String(eMinor).padStart(3,"0")} / ${String(nMajor).padStart(2,"0")} ${String(nMinor).padStart(3,"0")}`}
$("map").addEventListener("click",e=>{if(e.target.closest("button"))return;let box=$("map").getBoundingClientRect(),x=(e.clientX-box.left)/box.width,y=(e.clientY-box.top)/box.height;addWp({name:`WP ${document.querySelectorAll(".waypoint").length+1}`,grid:gridFromClick(e),alt:V("alt"),action:"HOLD"});draw()});
function parseGrid(s){let m=String(s).match(/(\d{2})\s+(\d{3}).*?(\d{2})\s+(\d{3})/);if(!m)return null;let east=+m[1]+(+m[2]/1000),north=+m[3]+(+m[4]/1000);return {x:(east/8)*100,y:(1-north/4)*100}}
function draw(){let pins=$("pins"),svg=$("lines");pins.innerHTML="";svg.innerHTML="";let pts=[];document.querySelectorAll(".waypoint").forEach((r,i)=>{let p=parseGrid(r.querySelector(".wg").value);if(p){pts.push(p);let d=document.createElement("div");d.className="pin";d.style.left=p.x+"%";d.style.top=p.y+"%";d.textContent=i+1;pins.append(d)}});if(pts.length>1){let pl=document.createElementNS("http://www.w3.org/2000/svg","polyline");pl.setAttribute("points",pts.map(p=>`${p.x},${p.y}`).join(" "));svg.append(pl)}}
["mission","datetime","type","status","notes","rules","formation","alt","weather","load","comms","aircraft","callsign"].forEach(id=>$(id).addEventListener("input",()=>{renderBrief();draw();if(id==="aircraft")updateAircraftMeta()}));
$("aircraft").addEventListener("change",updateAircraftMeta);
addWp({name:"START",alt:"500 AGL",action:"DEPART"});updateAircraftMeta();renderSaved();renderBrief();